# Generated by Django 5.2.2 on 2025-06-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='features',
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='features',
            field=models.ManyToManyField(related_name='package_details', to='offers_app.feature'),
        ),
    ]
