# Generated by Django 5.2.2 on 2025-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_alter_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
