# Generated by Django 5.2.2 on 2025-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(max_length=255),
        ),
    ]
