# Generated by Django 5.2.2 on 2025-07-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
    ]
